package com.skillmasterai.modules.distribution.internal;

import com.github.difflib.DiffUtils;
import com.github.difflib.UnifiedDiffUtils;
import com.github.difflib.patch.Patch;
import com.skillmasterai.modules.distribution.SkillDiff.Hunk;
import java.util.ArrayList;
import java.util.List;

/**
 * The line level: two texts in, unified-diff hunks out.
 *
 * <p>The only class that knows the diff library exists, which is the point of it being here rather
 * than in {@code DiffService} — swapping the algorithm, or writing one, is a change to this file and
 * nothing else.
 *
 * <p><strong>Nothing is normalised.</strong> Line endings, a missing final newline and a byte-order
 * mark all survive into the comparison, so a version that changed only its line endings <em>is</em> a
 * diff of every line — because that is what the bytes say, and the digest that identifies the version
 * says it too (ADR 0005). Rewriting either side to make the output prettier would produce a
 * comparison of something other than the two versions it claims to compare.
 */
public final class LineDiff {

    private LineDiff() {
    }

    /**
     * A text as lines, split at {@code \n} and at nothing else.
     *
     * <p>A trailing {@code \n} therefore yields a final empty element rather than being absorbed, so
     * "the file ends with a newline" and "it does not" are different lists — which is what makes that
     * difference appear in the diff instead of vanishing. {@code \r} is left where it is, for the same
     * reason: CRLF is content here, not formatting.
     *
     * @param text the decoded bytes; must not be null. Callers decide what may be decoded at all —
     *             see {@link com.skillmasterai.modules.distribution.DiffService}
     */
    public static List<String> lines(String text) {
        return List.of(text.split("\n", -1));
    }

    /**
     * The hunks between two versions of one file.
     *
     * <p>Empty when the two are line-for-line equal, which is a real answer and not a failure: two
     * contents can differ in bytes while every line matches (a trailing newline added, a CRLF run
     * converted back). Callers must not read an empty list as "not rendered" — that is {@code null}.
     *
     * <p>The unified diff is generated by the library and then <em>split</em>, not recomputed. The
     * two {@code ---}/{@code +++} lines it starts with are dropped because the relpath and the status
     * are already fields of the file this belongs to, and repeating them here would be a second place
     * they are written. Everything from the first {@code @@} on is kept verbatim: the header lines'
     * offsets and the body's prefixes are the algorithm's own account of what it did, and the reader's
     * job is to show it rather than to re-derive it.
     *
     * @param relpath the file's path, used only as the diff's filename — it appears in the dropped
     *                preamble and nowhere in the result
     * @param before  the lines of the version compared against; empty when it did not exist
     * @param after   the lines of the version being compared; empty when it was removed
     * @param context how many unchanged lines to keep around each change. Three is unified diff's
     *                classic value and what a review page shows
     */
    public static List<Hunk> hunksOf(String relpath, List<String> before, List<String> after,
            int context) {
        Patch<String> patch = DiffUtils.diff(before, after);
        if (patch.getDeltas().isEmpty()) {
            return List.of();
        }

        List<Hunk> hunks = new ArrayList<>();
        String header = null;
        List<String> body = new ArrayList<>();
        for (String line : UnifiedDiffUtils.generateUnifiedDiff(relpath, relpath, before, patch,
                context)) {
            if (line.startsWith("@@")) {
                if (header != null) {
                    hunks.add(new Hunk(header, body));
                }
                header = line;
                body = new ArrayList<>();
            } else if (header != null) {
                // Only reachable after the first header, so the preamble's "--- relpath" and
                // "+++ relpath" fall through and are dropped.
                body.add(line);
            }
        }
        if (header != null) {
            hunks.add(new Hunk(header, body));
        }
        return hunks;
    }
}
