-- V6's comment on this column said the id would be a ULID. It is not, and the code is what settled it.
--
-- The authorization's id is chosen by the framework — `OAuth2Authorization` is built with
-- `UUID.randomUUID()` before we are ever called — so `save` receives a UUID and there is nothing to
-- convert. Rewriting it inside `save` was considered and rejected: the framework holds the same
-- object in memory and uses its id for the rest of the request, so a store that changed it would be
-- handing back rows under a key the caller never sees.
--
-- A new migration rather than an edit to V6 for the reason every migration here is: V6 has been
-- applied, and Flyway refuses a changed checksum. That the wrong text is only a comment does not
-- matter — the comment is the description of the column, and a description that is wrong is worse
-- than none, because it is believed.

COMMENT ON COLUMN oauth_authorization.id IS
  'The authorization_id the code and both tokens carry. A UUID generated by the framework, not a ULID of ours: OAuth2Authorization is built with one before this service is called, and rewriting it here would hand rows back under a key the caller never sees. So the "ordered by creation" property a ULID would have given is not available; created_at is what to sort by.';
